[package]
name = "pdf2png"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
cairo-rs = { version = "0.18.5", features = ["pdf", "svg", "png"] }
poppler = { version = "0.4.0", features = ["render"] }
